# Case study on Supervised learning

##### Do the following in the iris dataset "iris.xls"

##### 1. Read the dataset to the python environment.

##### 2. Do necessary pre-processing steps.

##### 3. Find out which classification model gives the best result to predict iris species.(also do random forest algorithm)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1.  Read the dataset to the python environment

In [2]:
iris_data = pd.read_excel(r'C:\Users\Dell\Downloads\iris.xls')
iris_data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

## 2.  Do necessary pre-processing steps

In [3]:
iris_data.shape

(150, 5)

In [4]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
iris_data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [6]:
iris_data['SL'].fillna(iris_data['SL'].mean(),inplace=True)
iris_data['SW'].fillna(iris_data['SW'].mean(),inplace=True)
iris_data['PL'].fillna(iris_data['PL'].mean(),inplace=True)
iris_data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [7]:
x=iris_data.drop('Classification', axis=1)
y=pd.DataFrame(iris_data['Classification'])
x.describe()

SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [8]:
from sklearn.preprocessing import LabelEncoder
label_en = LabelEncoder()
a = ['Classification']
for i in np.arange(len(a)):
    y[a[i]]=label_en.fit_transform( y[a[i]])

In [9]:
x.columns

Index(['SL', 'SW', 'PL', 'PW'], dtype='object')

In [10]:
y['Classification'].value_counts()

0    50
1    50
2    50
Name: Classification, dtype: int64

## 3. Find out which classification model gives the best result to predict iris species.(also do random forest algorithm)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=2, test_size=0.20)

In [12]:
print('x_train :',x_train.shape)
print('y_train :',y_train.shape)
print('x_test :',x_test.shape)
print('y_test :',y_test.shape)

x_train : (120, 4)
y_train : (120, 1)
x_test : (30, 4)
y_test : (30, 1)


### Randon Forest Algorithm

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

<ipython-input-13-0dbe9a369c88>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train,y_train)


RandomForestClassifier()

In [14]:
y_pred = rf.predict(x_test)
y_pred

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,f1_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [16]:
f1_score(y_test,y_pred,average='micro')

0.9666666666666667

### Gradient Boosting Algorithm

In [17]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train, y_train)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GradientBoostingClassifier()

In [18]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [19]:
y_pred = gb.predict(x_test)

f1_score(y_test,y_pred,average='micro')

0.9333333333333333

### K-Nearest Neighbor(KNN) Algorithm

In [20]:
from sklearn.neighbors import KNeighborsClassifier
neig = KNeighborsClassifier()
neig.fit(x_train,y_train)
y_pred = rf.predict(x_test)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [21]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [22]:
f1_score(y_test,y_pred,average='micro')

0.9666666666666667

#### Insights:

By evaluating the dataset using three different classification models, it can be concluded that the kNN model and Random forest model gives the best result to predict iris species when compared to the other model. The scores provided by kNN and Random Forest is 96.66%.